### PR TITLE
fix: address pick issue when key not in object

### LINKED ISSUE #67: 'pick' picks provided key even if it is not in the object
Hello @rayepps! Thanks for this awesome library! 
I found an issue with `pick` function. It picks the keys that are not even in the object:

Code: `pick({ a:1, b:2 }, ['c'])`
Actual return value: `{ c: undefined }`
Expected return value: `{}`

Lodash's pick doesn't pick the key that is not in object. I expect that too.
Is it intended or it should be fixed? Thanks!

### PR DESCRIPTION
**Pull request by matteosacchetto**
## Description
With this PR I am trying to address the issue #67, where the `pick` function, when provided with a key not present in the source object, will return `{[key]: undefined}`. With these changes, if the key is not present in the object it will not appear in the final object

## Checklist
- [x] Changes are covered by tests if behavior has been changed or added
- [x] Tests have 100% coverage
- [x] The version in `package.json` has been bumped according to the changes made and standard semantic versioning rules

## Resolves
Resolves #67

### CODE REVIEW

**Comment by matteosacchetto** [comment]
Ok. so I commited the solution I had in mind for this problem. 
The issue I am facing now has to do with implementing the test to address the issue described in #67.

The problem is that, since `TKeys` extends `keyof T`, TS complains if in the test I add a key which is not present in the object
@rayepps do you have any suggestion on how to address this in a clean way?

**Comment by matteosacchetto** [comment]
Here are the issues
```bash
 src/tests/object.test.ts:160:46 - error TS2322: Type '"c"' is not assignable to type '"a" | "b"'.

    160       const result = _.pick({ a: 2, b: 3 }, ['c'])
                                                     ~~~
src/tests/object.test.ts:161:32 - error TS2345: Argument of type '{}' is not assignable to parameter of type 'Pick<{ a: number; b: number; }, "a" | "b">'.
      Type '{}' is missing the following properties from type 'Pick<{ a: number; b: number; }, "a" | "b">': a, b

    161       assert.deepEqual(result, {})
                                       ~~
```

Here is the test
```ts
test('handle key not in object', () => {
  const result = _.pick({ a: 2, b: 3 }, ['c'])
  assert.deepEqual(result, {})
})
```

**Comment by rayepps** [comment]
> TS complains if in the test I add a key which is not present in the object
@rayepps do you have any suggestion on how to address this in a clean way?

You can just type cast the things, its okay to get aggressive with TS type casting in the tests. Maybe try:

```ts
test('handle key not in object', () => {
  const result = _.pick({ a: 2, b: 3 } as any, ['c'])
  assert.deepEqual(result, {} as any)
})
```

File: src/object.ts [hunk 1]
```diff
@@ -156,7 +156,9 @@ export const pick = <T, TKeys extends keyof T>(
 ): Pick<T, TKeys> => {
   if (!obj) return {} as Pick<T, TKeys>
   return keys.reduce((acc, key) => {
-    return { ...acc, [key]: obj[key] }
+    if(typeof(obj[key]) !== 'undefined')
+      acc[key] = obj[key]
+    return acc;
```
Comment (rayepps) [inline src/object.ts:161]: I would use `Object.hasOwn` for this check that way we don't end up ignoring properties that exist but have an undefined value.

For example, I think this test will fail with the current implementation
```ts
test('does not ignore undefined values', () => {
      const result = _.pick({ a: 2, b: undefined }, ['b'])
      assert.deepEqual(result, { b: undefined })
})
```

Actually, might have to use the older `hasOwnProperty` function for node <16 compatability.

Screen Shot 2022-10-19 at 12 04 45 PM

Comment (matteosacchetto) [reply src/object.ts:161]: You are right! My intent was to keep undefined in the object, but my brain made a mistake... 🤦🏼

Comment (matteosacchetto) [reply src/object.ts:161]: `Object.hasOwn` requires tslib to be bumped to `es2022`, which I think is not compatible with node v12
So, I opted for the `.hasOwnProperty` method of the object class

**Comment by matteosacchetto** [comment]
What if I update the signature of pick to
```ts
export const pick = <T extends Record<string, unknown>, TKeys extends keyof T>
```
In order to restrict T to be a generic object?

`Record<string, unknown>` is one of the way of defining a generic object, like `{ [key: string]: unkwown}`

Let me know what you think and in case, if you have any preference on the way to represent a generic object

**Comment by rayepps** [comment]
@matteosacchetto ya I think that would be a good change 👍

**Review by rayepps — APPROVED** [review]

**Comment by rayepps** [comment]
This has been published to npm 🎉 in version `8.0.2`
